compile:
	gcc -Wall -pedantic-errors -o firstline firstline.c
	gcc -Wall -pedantic-errors -o lastline lastline.c
	gcc -Wall -pedantic-errors -o longestline longestline.c


run: compile
	./firstline
	./lastline
	./longestline

clean:
	rm -f firstline
	rm -f lastline
	rm -f longestline
